---
- name: 挂载ceph文件系统
  copy: 
    src: file/ceph.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644
- yum: 
    update_cache: yes
    name: libcephfs1
    state: installed
- name: copy key file
  copy: 
    src: file/ceph_key.txt
    dest: /tmp/
- shell: echo "192.168.1.150:6789,192.168.1.151:6789,192.168.1.152:6789:/ /usr/local/nginx/html/ ceph defaults,_netdev,name=admin,secret=$(cat /tmp/ceph_key.txt) 0 0" >> /etc/fstab
- shell: mount -a
