---
#
- name: 将nginx添加到systemd管理
  copy: 
    src: file/nginx.service
    dest: /usr/lib/systemd/system/
    owner: root
    group: root
    mode: 0644
- shell: systemctl daemon-reload
- name: start nginx service
  service: 
    name: nginx
    state: started
    enabled: yes
