---
- name: 安装ZooKeeper
  hosts: node1,node2,node3
  tasks: 
    - name: 修改主机名
      hostname: 
        name: "{{ host_name }}"
    - name: 安装java运行环境
      yum: 
        name: java-1.8.0-openjdk,java-1.8.0-openjdk
        state: installed
        update_cache: yes
    - name: 同步主机名映射
      copy: 
        src: /etc/hosts
        dest: /etc/
    - name: 安装zookeeper
      unarchive: 
        src: file/zookeeper-3.4.13.tar.gz
        dest: /usr/local/
    - shell: mv /usr/local/zookeeper-3.4.13 /usr/local/zookeeper
    - name: 同步配置文件
      tags: sync_conf
      template: 
        src: conf/zoo.cfg
        dest: /usr/local/zookeeper/conf/
        backup: yes
    - file: 
        path: /tmp/zookeeper
        state: directory
    - shell: echo "{{ myid }}" > /tmp/zookeeper/myid
    - shell: /usr/local/zookeeper/bin/zkServer.sh start
