---
- name: 安装管理节点
  hosts: mha
  tasks: 
    - name: 同步主机名解析
      copy:
        src: /etc/hosts
        dest: /etc/
    - name: 修改主机名
      hostname:
        name: "{{ host_name }}"
    - name: 发送密钥id_rsa
      copy:
        src: /root/.ssh/id_rsa
        dest: /root/.ssh/
        owner: root
        group: root
        mode: 0600
    - name: 取消ssh首次连接check
      shell: sed -ri '35a StrictHostKeyChecking no' /etc/ssh/ssh_config
    - shell: sed -ri '35a  UserKnownHostsFile /dev/null' /etc/ssh/ssh_config
    - service:
        name: sshd
        state: restarted
    - name: 安装依赖包
      yum: 
        name: mha4mysql-node
        state: installed
        update_cache: yes
    - shell: yum -y install perl-ExtUtils*
    - shell: yum -y install perl-CPAN*
#    - name: 安装mha4mysql-management
#      unarchive: 
#        src: file/mha4mysql-manager-0.56.tar.gz
#        dest: /root
