---
- name: 部署mycat读写分离
  hosts: mycat
  tasks:
    - name: 设置主机名
      hostname: 
        name: "{{ host_name }}"
    - name: 同步主机名解析
      copy: 
        src: /etc/hosts
        dest: /etc/
    - name: 安装依赖包
      yum: 
        name: java-1.8.0-openjdk
        state: installed
        update_cache: yes
    - name: 安装mycat
      unarchive: 
        src: file/Mycat-server-1.6-RELEASE-20161028204710-linux.tar.gz
        dest: /usr/local/
    - name: 同步配置文件
      tags: sync_conf
      notify: restart_ser
      template:
        src: "{{ item }}"
        dest: /usr/local/mycat/conf/
        mode: 0777
      with_items: 
        - "conf/server.xml"
        - "conf/schema.xml"
    - name: 启动服务
      shell: /usr/local/mycat/bin/mycat start
    - shell: echo "/usr/local/mycat/bin/mycat start" >> /etc/rc.local
  handlers:
    - name: restart_ser
      shell: /usr/local/mycat/bin/mycat restart
