---
- name: 部署kubernetes node节点
  hosts: docker
  tasks: 
    - name: 同步主机名解析
      copy: 
        src: /etc/hosts
        dest: /etc/
    - name: 安装软件包
      yum: 
        name: kubernetes-node
        update_cache: yes
        state: latest
    - name: 同步配置文件
      template: 
        src: "{{ item }}"
        dest: /etc/kubernetes
      with_items: 
        - "conf/config" 
        - "conf/kubelet"
        - "conf/kubelet.kubeconfig"
    - name: 启动服务
      service: 
        name: "{{ item }}"
        state: started 
        enabled: yes
      with_items: 
        - "kubelet"
        - "kube-proxy"
    - name: 安装flannel
      yum: 
        name: flannel
        state: latest
    - service:  
        name: docker
        state: stopped
    - name: 同步flannel配置文件
      copy: 
        src: conf/flanneld
        dest: /etc/sysconfig/
    - name: 启动服务
      service: 
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: 
        - "flanneld"
        - "docker"
        - "kubelet"
    - shell: iptables -P FORWARD ACCEPT
